config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    member do
     get :following, :followers
    end
    get :edit_profile
  end

  resources :relationships, only: [:create, :destroy]

  resources :picks do
    resources :comments, only: [:create]
  end

  resources :artists, only: [:show]

  resources :favorites, only: [:create, :destroy]

  root 'picks#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :favoriting_artists, class_name: "Favorite", foreign_key: "artist_id", dependent: :destroy
  has_many :users, through: :favoriting_artists
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :pick
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  acts_as_taggable
  acts_as_taggable_on :skills, :interests
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :picks

 has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

 has_many :followings, through: :following_relationships

 has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

 has_many :followers, through: :follower_relationships

 has_many :favorite_artists, class_name: "Favorite", foreign_key: "user_id", dependent: :destroy

 has_many :artists, through: :favorite_artists

 def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def favorite?(artist)
    favorite_artists.find_by(artist_id: artist.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :family_name, :family_name_kana, :first_name, :first_name_kana, :icon_image, :header])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :family_name, :family_name_kana, :first_name, :first_name_kana, :icon_image, :header])
   devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :family_name, :family_name_kana, :first_name, :first_name_kana, :icon_image, :header])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment: comment_params[:comment], pick_id: comment_params[:pick_id], user_id: current_user.id)
    redirect_to "/picks/#{@comment.pick.id}"
  end

  private
  def comment_params
    params.permit(:comment, :pick_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @user_id = current_user.id
    @artist_id = Artist.find(params[:favorite][:artist_id]).id
    @favorite = Favorite.new(user_id: @user_id, artist_id: @artist_id)

    if @favorite.save
      redirect_to user_edit_profile_path(current_user)
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])

    if @favorite.destroy
      redirect_to user_edit_profile_path(current_user)
    end
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController

  def index
    @picks = Pick.includes(:user).page(params[:page]).per(12).order("created_at DESC")
    @q = Pick.ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(7).order("created_at DESC")
    @songs
  end

  def user_params
    params.require(:user).permit(:name, :tag_list)
  end

  def new
    @pick =Pick.new
  end

  def create
    link = params[:pick].require(:url)
    get_product(link).save
  end

  def get_product(link)
    agent = Mechanize.new
    page = agent.get(link)
    title = page.title
    # KAI-YOU
    if page.at('.m-article-main img')
      image_url = page.at('.m-article-main img')[:src]
      pick = Pick.new(title: title, image_url: image_url, user_id: current_user.id, url: params[:url], url: params[:pick].require(:url), tag_list: params[:pick].require(:tag_list), poster_comment: params[:pick].require(:poster_comment))
    # YOUTUBE
    elsif page.at('meta[itemprop="videoId"]')
      video_url = page.at('meta[itemprop="videoId"]')[:content]
      image_url = "http://i.ytimg.com/vi/#{video_url}/mqdefault.jpg"

      pick = Pick.new(title: title, image_url: image_url, user_id: current_user.id, url: params[:url], url: params[:pick].require(:url), tag_list: params[:pick].require(:tag_list), video_url: video_url, poster_comment: params[:pick].require(:poster_comment))
      # CAMPFIRE
    elsif page.at('.thumbnail-in img')
      image_url = page.at('.thumbnail-in img')[:src]
      project_url = page.at('.embed-popup-iframe iframe')[:src]
      pick = Pick.new(title: title, image_url: image_url, user_id: current_user.id, url: params[:url], url: params[:pick].require(:url), tag_list: params[:pick].require(:tag_list), project_url: project_url, poster_comment: params[:pick].require(:poster_comment))
    else
      redirect_to root_path
    end
 
  end

  def show
    @pick = Pick.find(params[:id])
    @comments = @pick.comments.includes(:user)
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @nickname= @user.nickname
    @picks= @user.picks
    @user_image = @user.icon_image
    @header_image = @user.header
    @favorite_artists = @user.artists
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def edit_profile
    @q = Artist.ransack(params[:q])
    @searched_artists = @q.result(distinct: true)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/artists/show.html.erb
<div class="container" >
  <header class="image-bg-fluid-height" src="<%= @header_image %>">
    <div class="artist-name">
      <h3><%= @artist.artist_name %></h3>
      <a href="<%= @artist.artist_url %>">公式サイト</a>
    </div>
  </header>

  <div class="main-body">
  </div>
</div>

app/views/picks/_artist.html.erb
<table>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px; width: 50px;">1</h3>
    </th>  
    <th style="padding-left: 10px;">
      <%= image_tag 'artist_1.jpeg',:size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>SKY-HI</h3>
    </th>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">2</h3>
    </th>
    <th>
      <%= image_tag 'artist_2.jpg',:size =>'100x75'%>
    </th>
    <th style="text-align: center;">
      <h3>SALU</h3>
    </th>
  </tr>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">3</h3>
    </th>
    <th>
      <%= image_tag 'artist_3.jpg',:size =>'100x75' %>
    </th>
    <th style="text-align: center;">
      <h3>AKLO</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">4</h3>
    </th>
    <th style="padding-left: 25px;">
      <%= image_tag 'artist_4.jpg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>RAUDEF</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">5</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'artist_5.jpg',:size =>'75x50'%>
    </th>
    <th style="text-align: center;">
      <h3>KICK THE CAN CREW</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">6</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'artist_6.jpg',:size =>'75x50'%>
    </th>
    <th style="text-align: center;">
      <h3>BAD HOP</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">7</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'artist_7.jpg',:size =>'75x50'%>
    </th>
    <th style="text-align: center;">
      <h3>AmPm</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">8</h3>
    </th>
    <th style="padding-left: 25px;">
      <%= image_tag 'artist_8.jpeg', :size =>'50x50'%>
    </th>
    <th style="text-align: center;">
      <h3>KOHH</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">9</h3>
    </th>
    <th style="padding-left: 25px;">
      <%= image_tag 'artist_9.jpg', :size =>'50x50'%>
    </th>
    <th style="text-align: center;">
      <h3>DABO</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">10</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'artist_10.jpg',:size =>'75x50'%>
    </th>
    <th style="text-align: center;">
      <h3>ONE OK ROCK</h3>
    </th>
  </tr>
</table>

app/views/picks/_comment.html.erb
<div class="col-sm-6 col-md-3 col-lg-3">
  <div class="pick" style="border-radius: 5px;" >
    <div class="comment">
      <span class="question_text"><%= simple_format(comment.comment) %></span>
    </div>
      <div class="user-comment">
        <div class="profile">
          <br>
          <img src="<%= current_user.icon_image %>" alt="ユーザー画像" style="margin-left: 20px;">
          <div class="details">
            <div class="nickname" style="margin-right: 150px;" ><%= current_user.nickname %>
            </div>
            <div class="job" style="overflow: initial;">
              <%= current_user.job %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/picks/_lyric.html.erb
<table>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px; width: 50px;">1</h3>
    </th>  
    <th>
      <%= image_tag 'image_1.jpg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>Walking on Water</h3>
      SKY-HI
    </th>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">2</h3>
    </th>
    <th>
      <%= image_tag 'image_2.jpeg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>カミツレベルベット</h3>
      SKY-HI
    </th>
  </tr>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">3</h3>
    </th>
    <th>
      <%= image_tag 'image_3.jpeg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>Walk this way</h3>
      SALU
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">4</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_4.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Waka zo!!!</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">5</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_5.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>千%</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">6</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_6.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Mobb life</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">7</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_7.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Super Saiyan</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">8</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_8.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Best part of us</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">9</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_9.jpg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Cho Wevy de Gomenne</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">10</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_10.jpg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Your lane</h3>
    </th>
  </tr>
</table>

app/views/picks/_pick.html.erb
<% unless pick.project_url? %>
<div class="col-sm-6 col-md-3 col-lg-3">
  <div class="pick" style="border-radius: 5px;" >
      <a href="<%= pick.url %>">
        <img src="<%= pick.image_url %>" alt="" >
      </a>
      <div class="caption">
        <div class="title">
          <br>
          <a href="/picks/<%= pick.id %>">
            <%= truncate(pick.title, :length => 60 ) %>
          </a>
        </div>
        <br>
        <% if current_user %>
          <div class="user-comment" style="padding-bottom: 30px;">
            <div class="profile" >
              <img src="<%= current_user.icon_image %>" alt="ユーザー画像" style="margin-left: 20px;">
              <div class="details">
                <div class="nickname" style="margin-right: 150px;" ><%= current_user.nickname %>
                </div>
                <div class="job" style="overflow: initial;">
                  <%= current_user.job %>
                </div>
              </div>
            </div>
            <div class="comment_pick" style="overflow: initial;">
              サンプル
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>
<% end %>

app/views/picks/_song.html.erb
<table>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px; width: 50px;">1</h3>
    </th>  
    <th>
      <%= image_tag 'image_1.jpg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>Walking on Water</h3>
      SKY-HI
    </th>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">2</h3>
    </th>
    <th>
      <%= image_tag 'image_2.jpeg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>カミツレベルベット</h3>
      SKY-HI
    </th>
  </tr>
  <tr class="best">
    <th>
      <h3 style="padding-left: 20px;">3</h3>
    </th>
    <th>
      <%= image_tag 'image_3.jpeg', :size =>'75x75' %>
    </th>
    <th style="text-align: center;">
      <h3>Walk this way</h3>
      SALU
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">4</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_4.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Waka zo</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">5</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_5.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>千%</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">6</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_6.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Mobb life</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">7</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_7.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Super Saiyan</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">8</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_8.jpeg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Best part of us</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">9</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_9.jpg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Cho Wevy de Gomenne</h3>
    </th>
  </tr>
  <tr>
    <th>
      <h3 style="padding-left: 20px;">10</h3>
    </th>
    <th style="padding-left: 10px;">
      <%= image_tag 'image_10.jpg', :size =>'50x50' %>
    </th>
    <th style="text-align: center;">
      <h3>Your lane</h3>
    </th>
  </tr>
</table>

app/views/picks/create.html.erb
<div class="contents row">
  <div class="main-body">
    <div class="container">
      <div class="col-md-5 col-md-offset-5">
        <h3>投稿が完了しました。</h3>
      </div>
    <div class="col-md-5 col-md-offset-5">
      <a class="btn btn-primary" href="/">投稿一覧に戻る</a>
  </div>
</div>

app/views/picks/index.html.erb
<!-- Page Content -->
<div class="container">
  <div class="main-body">

    <ul class="nav nav-tabs" role="tablist">
      <li class="active" role="presentation">
        <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab"><h3>Latest Articles</h3></a>
      </li>
      <li role="presentation">
        <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab"><h3>Latest Propjects</h3></a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_a" role="tabpanel">
        <div class="row">
          <div class="row text-center">
            <% @articles.each do |pick| %>
              <%= render partial: "pick", locals: {pick:pick} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tab-pane" id="tab_b" role="tabpanel">
        <div class="row">
          <div class="row text-center">
            <% @picks.each do |pick| %>
              <%= render partial: "project", locals: {pick:pick} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>



    <ul class="nav nav-tabs" role="tablist">
      <li class="active" role="presentation">
        <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab"><h3>Top Songs</h3></a>
      </li>
      <li role="presentation">
        <a aria-controls="tab_d" data-toggle="tab" href="#tab_d" role="tab"><h3>Top Artists</h3></a>
      </li>
      <li role="presentation">
        <a aria-controls="tab_e" data-toggle="tab" href="#tab_e" role="tab"><h3>Top Lyrics</h3></a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_c" role="tabpanel">
        <%= render partial: "song" %>
      </div>
      <div class="tab-pane" id="tab_d" role="tabpanel">
        <p>
        <%= render partial: "artist" %>
        </p>
      </div>
      <div class="tab-pane" id="tab_e" role="tabpanel">
        <p>
        <%= render partial: "lyric" %>
        </p>
      </div>
    </div>


</div>

app/views/picks/new.html.erb
<div class="contents row">
  <div class="main-body">
    <div class="container">
      <%= form_for(@pick) do |f| %>
        <div class="col-md-5 col-md-offset-3">
          <h3>投稿する</h3>
        </div>

        <div class="col-md-5 col-md-offset-3">
          <%= f.label :pick, "URL" %>
          <%= f.text_field :url, class: "form-control" %>
        </div>

        <div class="col-md-5 col-md-offset-3">
          <%= f.label :pick, "コメント" %>
          <%= f.text_field :poster_comment, class: "form-control" %>
        </div>

        <div class="col-md-5 col-md-offset-3">
          <%= f.label :pick, "タグ" %>
          <%= f.text_field :tag_list, value: @pick.tag_list.join(','), class: "form-control" %>
        </div>

        <div class="col-md-5 col-md-offset-3">
          <%= button_tag type: "submit", class: "btn btn-info" do %>
            投稿する
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/picks/show.html.erb
<div class="container">
  <div class="main-body">
    <div class="show" style="border-radius: 5px;" >
      <% if @pick.video_url? %>
        <iframe width="560" height="315" style="border-radius: 5px;" src="https://www.youtube.com/embed/<%= @pick.video_url %>" frameborder="0" allowfullscreen></iframe>
      <% else %>
        <a href="<%= @pick.url %>">
          <div class="img-responsive" style="background-image: url(<%= @pick.image_url %>);"></div>
        </a>
      <% end %>
        <h3 style="text-align: center;" ><%= @pick.title %></h3>

<!--         <h5 style="margin-left: 20px;"><span><%= @pick.user.nickname %></span> さんのコメント</h5>
        <div style="margin-left: 20px;">
          <%= @pick.poster_comment %>
        </div> -->
    </div>

    <% if current_user.id != @pick.user_id %>
      <div class="show" style="border-radius: 5px; margin-top: 10px; padding-top: 12px; padding-bottom: 0;" >
        <div class="posting_form">
          <header class="profile">
            <img src="<%= current_user.icon_image %>" alt="ユーザー画像">
          </header>
          <%= form_tag("/picks/#{@pick.id}/comments", method: :post) do %>
            <textarea name="comment" placeholder="コメントする"></textarea>
            <input type="submit" value="SEND" >
          <% end %>
        </div>
      </div>
    <% end %>


    <div class="show" style="margin-top: 10px; padding-top: 10px; padding-right: 30px;" >
          <img src="<%= current_user.icon_image %>" alt="ユーザー画像" style=" height: 50px; width: 50px; margin-left: 20px;">
          <div class="comment clearfix">
            <%= @pick.poster_comment %>
          </div>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <%= render partial: "comment", locals: {comment:comment} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_favorite.html.erb
<%= form_for(current_user.favorite_artists.build(artist_id: artist.id)) do |f| %>
  <div><%= f.hidden_field :artist_id %></div>
  <%= f.submit "お気に入り登録", class: "favorite-btn", style: "margin: auto 0; background-color: #afeeee;" %>
<% end %>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <div class="follow-design">
    <a href="<%= following_user_path(@user) %>" style="color: gray; text-decoration: none">
      <strong id="following" class="stat" style="color: black">
        <%= @user.followings.count %>
      </strong>
      フォロー
    </a>
    <a href="<%= followers_user_path(@user) %>" style="color: gray; text-decoration: none">
      <strong id="followers" class="stat" style="color: black">
        <%= @user.followers.count %>
      </strong>
      フォロワー
    </a>
  </div>
  <div class="favorite-artists">
    <div col-sm-6 col-md-3 col-lg-3>
      <!-- あとでArtistテーブルからリンク付け -->
      <!-- **要編集** -->
      <!-- ************** -->
      <% @favorite_artists.each do |artist| %>
        <!-- <a href="<%= artist.artist_url %>"> -->
        <a href="<%= artist_path(artist) %>">
          <div class="favorite-artists-name"><%= artist.artist_name %></div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<div class="container" >
  <header class="image-bg-fluid-height" src="<%= @header_image %>">
    <div class="user-name">
      <h3>プロフィール編集</h3>
    </div>
  </header>

  <div class="main-body">

    <div class="searchbox">
        <%= search_form_for @q, url: {action: :edit_profile} do |f| %>
          <dt><%= f.search_field :artist_name_cont, placeholder: 'アーティストを検索' %></dt>
          <%= f.submit %>
        <% end %>
      </div>

      <div class="searched_result">
        <% @searched_artists.each do |artist| %>
          <li style = "font-size: 20px; list-style-type: none; display: flex; padding: 10px 0;">
            <div id="edit_profile_artist" style="margin: auto 0; padding-right: 20px;">
              <%= artist.artist_name %>
            </div>
            <div class="favorite-button" id="edit_profile_favorite" style="float: left; clear: both; margin: auto 0;">
              <% if current_user.favorite?(artist) %>
                <%= render 'unfavorite', artist: artist %>
              <% else %>
                <%= render 'favorite', artist: artist %>
              <% end %>
            </div>
          </li>
        <% end %>
      </div>
    </div>
    <div style="background-color: antiquewhite; width: 25%; margin: auto;">
      <a href="<%= user_path(current_user.id) %>" style=" font-size: 20px; text-align: center; display: inherit; cursor: pointer;">完了</a>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <a href="<%= user_path(user) %>">
        <img src="<%= user.icon_image %>" alt="">
      </a>
      <div class="caption follow_nickname">
        <h3><%= user.nickname %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show_follower.html.erb
<div class="follow_list">
  <% @user.followers.each do |user| %>
    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <a href="<%= user_path(user) %>">
          <img src="<%= user.icon_image %>" alt="">
        </a>
        <div class="caption follow_nickname">
          <h3><%= user.nickname %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>